language: node_js
node_js: '10'
cache: yarn
before_script:
- yarn
script:
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email: rishabhsrao@gmail.com
  api_key:
    secure: Fq3ZxjgxBYf2B5lDYX1Stxt+6i5sbvYmb+D8xhkNHszeuYtNC+ygm+Bzta+nd5K4BSWKu5BHTXS8pyRHEsn8dMwUnibPFXxe3ZX0p5F0atcmJMY+SKovStwzoWeipGW8Ts0dyeGWipQlVVoKXXrm8K51yXWRXEoL0a8YGQfzUPt9Nuiy8Q5u3lVqas/9VqcAroATRBwg0IXuFP2QrGJ9YxlGgkeazVpNonOni5AwPshOG3LYZVr5l+sjrLADcvpKKxo6FmvXLcS8OTI2HBbRyhhnlMMM2iBL3XigN5OoEVPeAao9Rf+c7EfoNNs12llqI7DbKfzR8aAgz/kLiy1bvGgTn7HX+WjV1GmqNoprYWlXTr1m3OL13urPdTvk7OfSPqrDzcOj1xrB6m1cnhBjz1hmJ7BOsm8Zgkyes8wBR2vFEMMBe+j4dAJTPJs1P1eGRVAz9FAuCdYd3d3tmmpxZEa0Wnw6pa2U3M6bdMtkjEzZaX46LNz2Ld06So/sIwKaszRyHO2c72ryTmCkGd5eCbbraw46zgfqi7YGO4meDgWkWBiPTXyL7qPRwzMnZpSDqvt+Mu2gYSFA7KRPuNLlHcfhj41QME9V7IadtAheaDo/1rsZIFIwbrV8eh/2F9aiMWf5+buLVONk62fKZB307OgVzgIlMO5tbLYFW3JKjgQ=
  on:
    tags: true
    repo: magica11y/magica11y
