language: node_js
node_js: '10'
cache: yarn
before_script:
- yarn
script:
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email: rishabhsrao@gmail.com
  api_key:
    secure: NJ+cr3m7jd3r14OxXanuJYSCwrIu7yVyQVVwb5xdJb5IYFE0R6IQCWueUcmXy8p48WaG/o6yqgmUcQDuHuMriktZ9RAFsU2/K2oBlYZvHVZSsXLwrK+/LZJjqtRCsC8yt0CqYYRyMKA2VoIVcoj09ND2IlNvQmc0bFxHVA+ocLOZkq3eeV2+Kv2GfYJHBQWhmStcRXSZwNT+g1HrWpbPszm8LH4oI+MfM4Wq2Rw3/Aknp1/tksKd5jSW+xNu8nXYOwBqbOvRBsMqgmTDfg3dIvF5tjFXd4GbgOyTS7FNy9XTJrIUmh6AMTISH7dDk2hbyUOtc2ydtkmvQb8bV2GWNNkMgr9ql5tCB7ex59PZRCqy8Gf5wESBuCvQgTbSyk5A66CFkffED4yqu5OyVFJ34z+W2QzzNnPRPFsQG/NtUevNTEAAet1m1VHTVLAiED2tUWVwuX71RPrjm6MuXdTXYNheMYqVvAbDnY8eTpH5I4K5wxeUIzfg56cfrh/fUrqr7McyZCWpURBjrC4KjwOXHmm/yzOAfFnw5CkIuUKZAdysJjFkUQD44YXhPKV1SU54AP3xXN8HLPI3aXHJYIYfczPugH9EOsir1hQAHliHh3wLehqTgbV7DwXdMxpShK4Zrhdk9a83RWqquvg7qNsL9ix7SRRFNC+MnDISSlfO+P8=
  on:
    tags: true
    repo: magica11y/magica11y
