remote_theme: magica11y/magica11y-jekyll-theme

title: "Magica11y"
description: "A suite of utility functions to detect 'user-preference' and 'environment' media features."

magica11y_api_methods:
  - prefersReducedMotion
  - lightLevel
  - environmentBlending
  - invertedColors
  - prefersReducedTransparency
  - prefersContrast
